### ISSUE TITLE
allure report generation 

### ISSUE THREAD

**Issue by srimanmittapally** [inspec/inspec-aws#200] opened 2020-04-20 12:08 UTC
allure report generation:
is it possible to add allure report ?

**Comment by skpaterson** [comment] 2020-04-20 12:11
Hi @srimanmittapally, closing as this is a duplicate of https://github.com/inspec/inspec/issues/4991.  This was transferred out of the InSpec AWS resource pack to the core InSpec repository pending the team's response to your feature request.

**Closed by skpaterson** 2020-04-20 12:11 UTC
